### ISSUE TITLE
NoClassDefFoundError: de/themoep/idconverter/IdMappings$IdType

### ISSUE THREAD

**Issue by tastybento** [BentoBoxWorld/Converter#12]
**Description**
Tried to do a vanilla conversion from 1.12 to 1.14.4 and I get this error:

```
> bsb convert
[19:21:14 INFO]: Getting the world settings
[19:21:15 INFO]: Saving BSkyBlock config
[19:21:15 INFO]: Converting challenges
[19:21:15 INFO]: Start importing Levels
[19:21:15 INFO]: Adding new object: Novice
[19:21:15 WARN]: Unexpected exception while parsing console command "bsb convert"
org.bukkit.command.CommandException: Unhandled exception executing 'bsb convert' in world.bentobox.bskyblock.commands.AdminCommand(bsbadmin)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.14.4.jar:git-Paper-225]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-225]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:456) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-225]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: de/themoep/idconverter/IdMappings$IdType
	at world.bentobox.a2b.converter.ItemDataParserUtil.parseItem(ItemDataParserUtil.java:82) ~[?:?]
	at world.bentobox.a2b.converter.ChallengesConverter.parseItems(ChallengesConverter.java:325) ~[?:?]
	at world.bentobox.a2b.converter.ChallengesConverter.makeLevels(ChallengesConverter.java:143) ~[?:?]
	at world.bentobox.a2b.converter.ChallengesConverter.convertChallengesAndLevels(ChallengesConverter.java:104) ~[?:?]
	at world.bentobox.a2b.commands.AdminConvertCommand.execute(AdminConvertCommand.java:116) ~[?:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:260) ~[?:?]
	at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:233) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-225]
	... 7 more
```

**Steps to reproduce the behavior:**
1. Follow the instructions [in the README](https://github.com/BentoBoxWorld/Converter/blob/develop/README.md)
2. Use a 1.14.4 server
3. See error when trying the conversion.

**Expected behavior**
No error.

**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): JSON
 - OS: [e.g. iOS] Linux
 - Java Version: [e.g. Java 8] java 11
 - BentoBox version: [e.g. 1.7.2.21] 1.9.0-SNAPSHOT
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
```
[19:28:18 INFO]: Running PAPER 1.14.4.
[19:28:18 INFO]: BentoBox version: 1.9.0-SNAPSHOT-LOCAL
[19:28:18 INFO]: Database: JSON
[19:28:18 INFO]: Loaded Game Worlds:
[19:28:18 INFO]: bskyblock_world (BSkyBlock): Overworld, Nether, End
[19:28:18 INFO]: Loaded Addons:
[19:28:18 INFO]: a2b 1.8.0-SNAPSHOT (ENABLED)
[19:28:18 INFO]: BSkyBlock 1.9.0-SNAPSHOT-b512 (ENABLED)
[19:28:18 INFO]: Challenges 0.9.0-SNAPSHOT-#390 (ENABLED)
[19:28:18 INFO]: Level 1.8.0-SNAPSHOT-b291 (ENABLED)
[19:28:18 INFO]: Warps 1.8.2-SNAPSHOT-b199 (ENABLED)
```
 - Other plugins? [Do '/plugins' and copy/paste from the console]
BentoBox

**Additional context**
I notice that there is reference in the POM to an item converter and @BONNe writes:

```
        <!--   Item Converter. Used JitPack as my version is using 1.14 data values    -->
        <dependency>
            <groupId>com.github.BONNe.IDConverter</groupId>
            <artifactId>application</artifactId>
            <version>${itemconverter.version}</version>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>de.themoep.idconverter</groupId>-->
<!--            <artifactId>mappings</artifactId>-->
<!--            <version>${itemconverter.version}</version>-->
<!--        </dependency>-->
```

**Comment by tastybento** [comment]
@BONNe Can you help me understand why this isn't working? Does the POM need changing to support 1.14.4 servers?

**Comment by tastybento** [comment]
I found the problem - during a merge of Master and Develop the shade plugin was removed in the POM. I'll add it back in.
