### ISSUE TITLE
Can't Run Command "/bsb convert"

### ISSUE THREAD

**Issue by brayjamindev** [BentoBoxWorld/Converter#2]
I'm trying to convert my ASkyBlock data to BSkyBlock, obviously. I found this converter, and followed all steps to successfully convert the data.

I ran the command `/bsb convert` as well as `/bsbadmin convert`, but I get nothing except this error in the console.

`[02:04:05 WARN]: Unexpected exception while parsing console command "bsbadmin convert"
org.bukkit.command.CommandException: Unhandled exception executing 'bsbadmin convert' in world.bentobox.bskyblock.commands.AdminCommand(bsbadmin)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:161) ~[patched_1.13.2.jar:git-Paper-627]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:734) ~[patched_1.13.2.jar:git-Paper-627]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:696) ~[patched_1.13.2.jar:git-Paper-627]
        at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:483) ~[patched_1.13.2.jar:git-Paper-627]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440) ~[patched_1.13.2.jar:git-Paper-627]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-627]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-627]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodError: world.bentobox.bentobox.database.objects.Island.setGameMode(Ljava/lang/String;)V
        at world.bentobox.a2b.commands.AdminConvertCommand.processIsland(AdminConvertCommand.java:330) ~[?:?]
        at world.bentobox.a2b.commands.AdminConvertCommand.convertplayers(AdminConvertCommand.java:278) ~[?:?]
        at world.bentobox.a2b.commands.AdminConvertCommand.execute(AdminConvertCommand.java:107) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:251) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.2.jar:git-Paper-627]
        ... 7 more`

I don't know what this means exactly, or what I can do. Help would be appreciated lol...

**Comment by tastybento** [comment]
It looks like the version of BentoBox you are using is incorrect. It should be 1.5.0. You can check the version by looking at the name of the file or doing **bbox version**. In fact, please share that output from the console.
