### ISSUE TITLE
Incompatibility with 1.16.0+

### ISSUE THREAD

**Issue by BONNe** [BentoBoxWorld/Converter#20]
**Description**
It looks like Converter is not compatible with BentoBox 1.16.0+.

**Steps to reproduce the behavior:**
Use BentoBox 1.16.1 as the main plugin.
Start converting data.

**Additional context**
```
java.lang.NullPointerException
  at world.bentobox.bentobox.database.objects.Island.updateMaxEverProtectionRange(Island.java:918)
  at world.bentobox.bentobox.database.objects.Island.setProtectionRange(Island.java:908)
  at world.bentobox.a2b.commands.AdminConvertCommand.processIsland(AdminConvertCommand.java:345)
  at world.bentobox.a2b.commands.AdminConvertCommand.convertplayers(AdminConvertCommand.java:293)
  at world.bentobox.a2b.commands.AdminConvertCommand.execute(AdminConvertCommand.java:121)
  at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:266)
  at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:239)
  at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
```

**Comment by tastybento** [comment]
This should fix it.
