### ISSUE TITLE
Can't run /bsb convert on 1.14.4 / bsb 1.6.0

### ISSUE THREAD

**Issue by runelynx** [BentoBoxWorld/Converter#3]
**Description**
Just converted from ASB -> BSB. Followed all instructions, including updating server to 1.13.2 w/ forceUpgrade, and the same to 1.14.4

**Steps to reproduce the behavior:**
Start server. Wait for startup completion and BentoBox logo.
Run /bsb convert from console.

**Expected behavior**
Conversion from ASK

**Screenshots**
![image](https://user-images.githubusercontent.com/5877481/63232050-d7417a00-c1d8-11e9-8924-5e2d3ff1c124.png)

[23:52:09 WARN]: Unexpected exception while parsing console command "bsb convert"
org.bukkit.command.CommandException: Unhandled exception executing 'bsb convert' in world.bentobox.bskyblock.commands.AdminCommand(bsbadmin)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.14.4.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701) ~[patched_1.14.4.jar:git-Paper-172]
        at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:456) ~[patched_1.14.4.jar:git-Paper-172]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.4.jar:git-Paper-172]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-172]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-172]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NoSuchMethodError: world.bentobox.bskyblock.Settings.setNetherTrees(Z)V
        at world.bentobox.a2b.commands.AdminConvertCommand.getConfigs(AdminConvertCommand.java:132) ~[?:?]
        at world.bentobox.a2b.commands.AdminConvertCommand.execute(AdminConvertCommand.java:100) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:260) ~[?:?]
        at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:233) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-172]
        ... 7 more

**Server Information:**

Java 8 
![image](https://user-images.githubusercontent.com/5877481/63232058-eb857700-c1d8-11e9-8940-31a32df7fb43.png)

**Additional context**

**Comment by tastybento** [comment]
Thanks for the report. I'll fix this now!

**Comment by tastybento** [comment]
Please try the latest release: https://github.com/BentoBoxWorld/Converter/releases/tag/1.6.0

**Comment by runelynx** [comment]
Thanks! Initial results are good. Will log in and check it out

![image](https://user-images.githubusercontent.com/5877481/63237499-2b5b5700-c1f7-11e9-9b3c-13ee512f425a.png)

**Comment by runelynx** [comment]
Converter worked; then also imported Challenges.yml and that worked.

But player completions of challenges has not imported in. How can I get those in?

**Comment by tastybento** [comment]
That’s not covered yet, but it looks like Bonne saw your comment and he’s working on it. See #5
